# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakesapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cakes_Data',
            new_name='Cake',
        ),
    ]
